[phases.setup]
nixPkgs = ["python311", "git"]

[phases.build]
cmds = [
  "pip install --no-cache-dir --upgrade pip",
  "pip install --no-cache-dir -r requirements-minimal.txt"
]

[start]
cmd = "python app.py"
